### ISSUE TITLE
ERROR:root:__call__() missing 1 required positional argument: 'value'

### ISSUE THREAD

**Issue by Yuan-Meng** [dnanhkhoa/nb_black#22]
When I ran `%reload_ext lab_black` in my Jupyterlab, I got an error message:
```
ERROR:root:__call__() missing 1 required positional argument: 'value'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/lab_black.py", line 218, in format_cell
    formatted_code = _format_code(cell)
  File "/opt/anaconda3/lib/python3.7/site-packages/lab_black.py", line 29, in _format_code
    return format_str(src_contents=code, mode=FileMode())
TypeError: __call__() missing 1 required positional argument: 'value'
```
<img width="819" alt="Screen Shot 2020-04-11 at 6 15 39 PM" src="https://user-images.githubusercontent.com/21133947/79058302-28e3bc80-7c21-11ea-956a-6af029b8b631.png">

Here's line 29:
<img width="773" alt="Screen Shot 2020-04-11 at 6 22 19 PM" src="https://user-images.githubusercontent.com/21133947/79058348-b7f0d480-7c21-11ea-91cb-f61fb872fc43.png">

Here's line 218:
<img width="735" alt="Screen Shot 2020-04-11 at 6 22 28 PM" src="https://user-images.githubusercontent.com/21133947/79058352-c0e1a600-7c21-11ea-8b8d-c78aaf22fe04.png">

Which function misses what argument? Also, I just updated to Jupyterlab to 2.1.0 so I don't know if there are weird incompatibility issues. Did anyone encounter this? Thanks!!

**Comment by ashwinidathatri** [comment]
I have been receiving the same error as well.  I doubt if it has anything to do with compatibility of the version.  Anyway currently I am using JupyterLab version 1.2.16

Any suggestions on this would be helpful.

**Comment by terhorst** [comment]
This is caused by having an old version of `black`. `pip install -U black` fixed it for me. To the maintainers: I don't know when `black` changed the API for `FileMode()` but moving from version 18.6b4 to 19.10b0 made this error go away.
